version: '3.1'
services:
  appka:
    build:
      context: ./appka
    ports:
      - "8080:8080"
    container_name: appka

  mydb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 3030:8080
    depends_on:
      - "mydb"
    container_name: adminer